test run script
Signed-off-by: barakda <barak.davidov@gmail.com>

diff --git a/.github/workflows/build-container.yml b/.github/workflows/build-container.yml
--- a/.github/workflows/build-container.yml
+++ b/.github/workflows/build-container.yml
@@ -668,9 +668,9 @@ jobs:
           sudo /root/cephadm/atomTestsRun.sh
 
       - name: Artifact logs copy
-        if: success() || failure()
+        # if: success() || failure()
         run: |
-          sudo cp -r /root/.ssh/atom_backup/artifact /tmp/
+          echo ${{ secrets.APPUSERPWD }} | sudo -S cp -r /root/.ssh/atom_backup/artifact /tmp/
           sudo chmod -R +rx /tmp/artifact
     
       # - name: Set artifact path permissions
